spring.application.name=WeatherDiary
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3307/weather_diary?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.show-sql=true
spring.jpa.database=mysql
openweathermap.key=4d3faf7197af08098f1e0b2348914f60
logging.config=classpath:logback-spring.xml